name: Deploy to Google Cloud

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # nécessaire pour OIDC
  contents: read    # permet de lire le code source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/811027683539/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@hbe-certif-sec-ebook-26164.iam.gserviceaccount.com"

      - name: Verify authentication
        run: |
          gcloud auth list
          curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            https://www.googleapis.com/oauth2/v3/userinfo | jq .

      - name: Deploy (example)
        run: |
          echo "Déploiement simulé..."
